language: ruby

rvm:
  - 2.2

before_script:
  - gem install awesome_bot

script:
- awesome_bot README.md --allow-dupe --allow-redirect --white-list https://coinkite.com/developers,https://publisher.yp.com/,https://azure.microsoft.com/en-us/services/cognitive-services/,https://developers.soundcloud.com,http://www.giantbomb.com/api/